### ISSUE TITLE
Modcom community form endpoint throwing error 400 

### ISSUE THREAD

**Issue by mouhannad-sh** [data-gov-my/datagovmy-back#236]
Hi there 👋🏻 

I tried to fill the community form to apply but I got a 400 status code error.

<img width="753" alt="image" src="https://github.com/data-gov-my/datagovmy-back/assets/18495740/0fa92514-9707-4d80-81f1-a89aae8de56e">

<img width="434" alt="image" src="https://github.com/data-gov-my/datagovmy-back/assets/18495740/ec1f4296-4bb5-4ecc-9e49-3c508d179118">

this is an awesome project by the way, looking forward for what will come from it in the future 🚀

**Comment by eujiaxin** [comment]
You should be able to submit the form now :)
